on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: ci

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: dtolnay/rust-toolchain@7b1c307e0dcbda6122208f10795a713336a9b35a # master
        with:
          toolchain: stable
      - run: cargo test --locked --workspace
      - run: cargo build --locked --workspace

  # fmt and clippy
  fmt-clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: dtolnay/rust-toolchain@7b1c307e0dcbda6122208f10795a713336a9b35a # master
        with:
          toolchain: stable
          components: rustfmt, clippy
      - run: cargo fmt --all --check
      - run: cargo clippy --workspace -- -D warnings
