on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: ci

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: dtolnay/rust-toolchain@21dc36fb71dd22e3317045c0c31a3f4249868b17 # master
        with:
          toolchain: stable
      - run: cargo test --locked --workspace
      - run: cargo build --locked --workspace

  # fmt and clippy
  fmt-clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: dtolnay/rust-toolchain@21dc36fb71dd22e3317045c0c31a3f4249868b17 # master
        with:
          toolchain: stable
          components: rustfmt, clippy
      - run: cargo fmt --all --check
      - run: cargo clippy --workspace -- -D warnings
